### ISSUE TITLE
Status of Godel Project?

### ISSUE THREAD

**Issue by melvinma** [ros-industrial-attic/godel#244]
It appears that this project has been inactive for half a year now. Could someone summarize what is going on? Milestone 4 achieved and no further plan? Anything else a new comer needs to know? Thanks.

**Comment by melvinma** [comment]
This is how I was able to successfully compile this code. I have NOT thoroughly test the codes yet.

- as [previously mentioned "Duplicate Libsocket"](https://github.com/ros-industrial-consortium/godel/issues/245) , there needs a small change to avoid conflict with libsocket++ installed in OS;
- Switch Descartes

```
original:
     git: {local-name: descartes, uri: 'https://github.com/Jmeyer1292/descartes.git', version: godel_refactor_omp}
new:
     git: {local-name: descartes, uri: 'https://github.com/ros-industrial-consortium/descartes.git', version: kinetic_devel}
```

- need to change at least two files because of Descartes change in the new source -

```
file: descartes/descartes_planner/include/descartes_planner/ladder_graph_dag_search.h
         original:  double run();
         new:       double run(const std::vector<double>& seed_weights = {});
```

```
file: descartes/descartes_planner/src/ladder_graph_dag_search.cpp
         replace funtion run() to run(const std::vector<double>& seed_weights) 
         from    https://github.com/Jmeyer1292/descartes/blob/godel_refactor_omp/descartes_planner/src/ladder_graph_dag_search.cpp
```
